In [489]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [490]:
# https://www.kaggle.com/code/gauravduttakiit/movie-recommendation-system-collaborative-filter/notebook

In [491]:
df=pd.read_csv('movies.csv')

In [492]:
df
# df.shape

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
10324,146684,Cosmic Scrat-tastrophe (2015),Animation|Children|Comedy
10325,146878,Le Grand Restaurant (1966),Comedy
10326,148238,A Very Murray Christmas (2015),Comedy
10327,148626,The Big Short (2015),Drama
10328,149532,Marco Polo: One Hundred Eyes (2015),(no genres listed)

In [493]:
rating_df=pd.read_csv('ratings.csv')
rating_df

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105334     668   142488     4.0  1451535844
105335     668   142507     3.5  1451535889
105336     668   143385     4.0  1446388585
105337     668   144976     2.5  1448656898
105338     668   148626     4.5  1451148148

[105339 rows x 4 columns]

In [494]:
df.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [495]:
rating_df.isnull().sum()

userId       0
movieId      0
rating       0
timestamp    0
dtype: int64

In [496]:
df=df.merge(rating_df,on='movieId')

In [497]:
df.loc[df['movieId']==2153,:]

,movieId,title,genres,userId,rating,timestamp
48102,2153,"Avengers, The (1998)",Action|Adventure,62,1.0,1267564601
48103,2153,"Avengers, The (1998)",Action|Adventure,109,1.0,940500928
48104,2153,"Avengers, The (1998)",Action|Adventure,130,2.0,941903696
48105,2153,"Avengers, The (1998)",Action|Adventure,310,2.5,1124192794
48106,2153,"Avengers, The (1998)",Action|Adventure,458,1.0,953243615
48107,2153,"Avengers, The (1998)",Action|Adventure,482,2.0,974652590
48108,2153,"Avengers, The (1998)",Action|Adventure,488,2.0,910638829
48109,2153,"Avengers, The (1998)",Action|Adventure,560,3.5,1067535079
48110,2153,"Avengers, The (1998)",Action|Adventure,597,2.0,965118729
48111,2153,"Avengers, The (1998)",Action|Adventure,607,1.0,974711692
48112,2153,"Avengers, The (1998)",Action|Adventure,668,1.0,1093478774

In [498]:
# def custom_tokenizer(text):

#     return text.split('|')

In [499]:
# from sklearn.feature_extraction.text import CountVectorizer
# cv=CountVectorizer(max_features=4000,stop_words='english',tokenizer=custom_tokenizer)

In [500]:
# vectors2 = cv.fit_transform(df['genres']).toarray()

In [501]:
# cv.get_feature_names_out()

In [502]:
# vectors2.shape

In [503]:
df.isnull().sum()

movieId      0
title        0
genres       0
userId       0
rating       0
timestamp    0
dtype: int64

In [504]:
len(df.dropna())/len(df)

1.0

In [505]:
type(df['genres'][0])

str

In [506]:
df_genres = df['genres'].str.get_dummies(sep='|')
df_genres

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
1,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
4,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105334,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
105335,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
105336,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
105337,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
105338,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [507]:
df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,2,5.0,859046895
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,1303501039
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,8,5.0,858610933
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,11,4.0,850815810
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,14,4.0,851766286
...,...,...,...,...,...,...
105334,148238,A Very Murray Christmas (2015),Comedy,475,3.0,1451213043
105335,148626,The Big Short (2015),Drama,458,4.0,1452014749
105336,148626,The Big Short (2015),Drama,576,4.5,1451687664
105337,148626,The Big Short (2015),Drama,668,4.5,1451148148
105338,149532,Marco Polo: One Hundred Eyes (2015),(no genres listed),475,4.0,1451223429

In [508]:
df=pd.merge(df,df_genres,left_index=True,right_index=True)

In [509]:
df= df.drop('genres',axis=1)
df

,movieId,title,userId,rating,timestamp,(no genres listed),Action,Adventure,Animation,Children,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,Toy Story (1995),2,5.0,859046895,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,Toy Story (1995),5,4.0,1303501039,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,Toy Story (1995),8,5.0,858610933,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,Toy Story (1995),11,4.0,850815810,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,1,Toy Story (1995),14,4.0,851766286,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105334,148238,A Very Murray Christmas (2015),475,3.0,1451213043,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105335,148626,The Big Short (2015),458,4.0,1452014749,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105336,148626,The Big Short (2015),576,4.5,1451687664,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105337,148626,The Big Short (2015),668,4.5,1451148148,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105338,149532,Marco Polo: One Hundred Eyes (2015),475,4.0,1451223429,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [510]:
df['title'][0][-5:-1]

'1995'

In [511]:

def extract_year(obj):
    return obj[-5:-1]

In [512]:


df['year']=df['title'].apply(lambda x: x[-5:-1])

In [513]:
df['title']=df['title'].apply(lambda x: x[:-7])

In [514]:
df

,movieId,title,userId,rating,timestamp,(no genres listed),Action,Adventure,Animation,Children,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
0,1,Toy Story,2,5.0,859046895,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
1,1,Toy Story,5,4.0,1303501039,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
2,1,Toy Story,8,5.0,858610933,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
3,1,Toy Story,11,4.0,850815810,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
4,1,Toy Story,14,4.0,851766286,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105334,148238,A Very Murray Christmas,475,3.0,1451213043,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105335,148626,The Big Short,458,4.0,1452014749,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105336,148626,The Big Short,576,4.5,1451687664,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105337,148626,The Big Short,668,4.5,1451148148,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105338,149532,Marco Polo: One Hundred Eyes,475,4.0,1451223429,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015

In [515]:
vector = rating_df.pivot(index='movieId',columns='userId',values='rating')
vector

userId,1,2,3,4,5,6,7,8,9,10,...,659,660,661,662,663,664,665,666,667,668
movieId,,,,,,,,,,,,,,,,,,,,,
1,NaN,5.0,NaN,NaN,4.0,NaN,NaN,5.0,NaN,NaN,...,NaN,NaN,4.0,5.0,3.0,NaN,NaN,NaN,NaN,3.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,3.0
3,NaN,2.0,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,3.0,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146684,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.5
149532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [516]:
# type(vector)
print(vector.index)
print(vector.columns)

Int64Index([     1,      2,      3,      4,      5,      6,      7,      8,
                 9,     10,
            ...
            144482, 144656, 144976, 146344, 146656, 146684, 146878, 148238,
            148626, 149532],
           dtype='int64', name='movieId', length=10325)
Int64Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
            ...
            659, 660, 661, 662, 663, 664, 665, 666, 667, 668],
           dtype='int64', name='userId', length=668)

In [517]:
number_of_movies_rated=rating_df.groupby('movieId')['rating'].agg('count')
number_of_movies_rated

movieId
1         232
2          92
3          58
4          11
5          62
         ...
146684      1
146878      1
148238      1
148626      3
149532      1
Name: rating, Length: 10325, dtype: int64

In [518]:
rating_df

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105334     668   142488     4.0  1451535844
105335     668   142507     3.5  1451535889
105336     668   143385     4.0  1446388585
105337     668   144976     2.5  1448656898
105338     668   148626     4.5  1451148148

[105339 rows x 4 columns]

In [519]:
number_of_usr_rated=rating_df.groupby('userId')['rating'].agg('count')
min_criteria=number_of_usr_rated.quantile(0.25)
print(number_of_usr_rated)

userId
1       113
2        29
3        73
4       124
5        68
       ...
664      74
665     227
666     225
667      74
668    5678
Name: rating, Length: 668, dtype: int64

In [520]:
number_of_movies_rated[number_of_movies_rated>min_criteria].index

Int64Index([     1,      2,      3,      5,      6,      7,     10,     11,
                16,     17,
            ...
             71535,  72998,  73017,  74458,  79132,  81845,  89745,  91529,
             99114, 109487],
           dtype='int64', name='movieId', length=728)

In [521]:
vector=vector.loc[number_of_movies_rated[number_of_movies_rated>min_criteria].index,:]
vector

userId,1,2,3,4,5,6,7,8,9,10,...,659,660,661,662,663,664,665,666,667,668
movieId,,,,,,,,,,,,,,,,,,,,,
1,NaN,5.0,NaN,NaN,4.0,NaN,NaN,5.0,NaN,NaN,...,NaN,NaN,4.0,5.0,3.0,NaN,NaN,NaN,NaN,3.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,3.0
3,NaN,2.0,NaN,NaN,NaN,NaN,NaN,4.0,3.0,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0
5,NaN,3.0,3.0,NaN,NaN,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,2.5
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,...,2.5,NaN,4.0,5.0,NaN,NaN,NaN,NaN,NaN,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0
89745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
91529,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
99114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.5
109487,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0

In [522]:
vector=vector.fillna(value=0)

In [523]:
df

,movieId,title,userId,rating,timestamp,(no genres listed),Action,Adventure,Animation,Children,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
0,1,Toy Story,2,5.0,859046895,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
1,1,Toy Story,5,4.0,1303501039,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
2,1,Toy Story,8,5.0,858610933,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
3,1,Toy Story,11,4.0,850815810,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
4,1,Toy Story,14,4.0,851766286,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105334,148238,A Very Murray Christmas,475,3.0,1451213043,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105335,148626,The Big Short,458,4.0,1452014749,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105336,148626,The Big Short,576,4.5,1451687664,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105337,148626,The Big Short,668,4.5,1451148148,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105338,149532,Marco Polo: One Hundred Eyes,475,4.0,1451223429,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015

In [524]:
genres_df=df.drop(['title','userId','rating','timestamp'],axis=1)
genres_df.drop_duplicates(inplace=True)
genres_df
t=genres_df.set_index('movieId')
t

,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
movieId,,,,,,,,,,,,,,,,,,,,,
1,0,0,1,1,1,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1995
2,0,0,1,0,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1995
3,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1995
4,0,0,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1995
5,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146684,0,0,0,1,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
146878,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1966
148238,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
148626,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,2015
149532,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015

In [525]:
# new_vector=pd.Series()
# for index,row in vector.iterrows():
#     print(index)

#     z=genres_df.loc[genres_df['movieId']==index,:]
#     print(row.shape)
    
#     row=row.append(pd.Series(z.iloc[0,1:]))
#     print(row)

#     print('now ')

#     # new_vector=new_vector.app
#     print(vector.loc[index].shape)
#     vector.loc[index]=vector.loc[index].append(pd.Series(z.iloc[0,1:]))
#     print(vector.loc[index])
#     break

In [526]:
z=genres_df.loc[genres_df['movieId']==3,:]
z.shape

(1, 22)

In [527]:
x=vector.iloc[0]
print(x.shape)
x=x.append(pd.Series(z.iloc[0,1:]))
print(x.shape)
x
# seris

(668,)
(689,)

/var/folders/w4/lbqrw9sd4j58jmmm2ls54fxm0000gn/T/ipykernel_58735/2642333695.py:3: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  x=x.append(pd.Series(z.iloc[0,1:]))

1            0.0
2            5.0
3            0.0
4            0.0
5            4.0
            ...
Sci-Fi         0
Thriller       0
War            0
Western        0
year        1995
Length: 689, dtype: object

In [528]:
vector

userId,1,2,3,4,5,6,7,8,9,10,...,659,660,661,662,663,664,665,666,667,668
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.0,5.0,0.0,0.0,4.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,4.0,5.0,3.0,0.0,0.0,0.0,0.0,3.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,3.0
3,0.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
5,0.0,3.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.5
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,2.5,0.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81845,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
89745,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
91529,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
99114,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5
109487,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [529]:
vector2=vector.merge(t,left_index=True,right_index=True)

In [530]:
vector2

,1,2,3,4,5,6,7,8,9,10,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.0,5.0,0.0,0.0,4.0,0.0,0.0,5.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1995
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1995
3,0.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,0.0,...,0,0,0,0,1,0,0,0,0,1995
5,0.0,3.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1995
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,0,0,0,0,0,0,1,0,0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81845,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,2010
89745,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,1,0,0,0,2012
91529,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,2012
99114,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,1,2012
109487,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,1,0,0,0,2014

In [531]:
vector.index.get_loc(1)
vector3=vector.values

In [532]:
vector2=vector2.values

In [533]:
vector2.shape

(728, 689)

In [534]:
from sklearn.metrics.pairwise import cosine_similarity

In [535]:
similarity=cosine_similarity(vector2)

In [536]:
similarity.shape

(728, 728)

In [537]:
list(enumerate(similarity[0]))

[(0, 0.9999999999999999),
 (1, 0.9995916341242957),
 (2, 0.9995850079389759),
 (3, 0.9995927613974778),
 (4, 0.99955298375433),
 (5, 0.9995882725696232),
 (6, 0.9995464198920769),
 (7, 0.9995448373262572),
 (8, 0.9995321576154007),
 (9, 0.9995724651709197),
 (10, 0.9995663947088358),
 (11, 0.9995402577516243),
 (12, 0.9995421914661081),
 (13, 0.9995471501933031),
 (14, 0.9995664327668942),
 (15, 0.9995473737235012),
 (16, 0.9995469311331923),
 (17, 0.9995156363042926),
 (18, 0.99959114344946),
 (19, 0.9995658400944066),
 (20, 0.9995796134739942),
 (21, 0.9995643839951337),
 (22, 0.9995408096843862),
 (23, 0.9995036562603513),
 (24, 0.9995677433154537),
 (25, 0.9994837306660652),
 (26, 0.9995692810997423),
 (27, 0.9995691232720872),
 (28, 0.9995775148280353),
 (29, 0.9995843149489536),
 (30, 0.9995886671001932),
 (31, 0.999619025043171),
 (32, 0.9995777341272125),
 (33, 0.9994955255715002),
 (34, 0.9995075163797479),
 (35, 0.9995716987270762),
 (36, 0.9995962799488355),
 (37, 0.9995505441318273),
 (38, 0.9995319772733751),
 (39, 0.9995477504137966),
 (40, 0.9995491434626457),
 (41, 0.9995616228165167),
 (42, 0.9995436349769321),
 (43, 0.9994826388870599),
 (44, 0.9995587671379366),
 (45, 0.9995490602254395),
 (46, 0.999562658188014),
 (47, 0.9995485627157548),
 (48, 0.9995422852697113),
 (49, 0.9995592993247073),
 (50, 0.9995698776315879),
 (51, 0.9995339121305692),
 (52, 0.9995345001972965),
 (53, 0.9995702229943747),
 (54, 0.9995714528234372),
 (55, 0.9995674915638426),
 (56, 0.9995738874321667),
 (57, 0.9995555630821046),
 (58, 0.9995330847129063),
 (59, 0.9995702808050446),
 (60, 0.9995568037693966),
 (61, 0.9995399946176144),
 (62, 0.9995079873865813),
 (63, 0.9995499926317171),
 (64, 0.999530646064675),
 (65, 0.9995811703402167),
 (66, 0.9995134761904751),
 (67, 0.9995199329811393),
 (68, 0.9995249564326684),
 (69, 0.9995083715359891),
 (70, 0.9995309161405174),
 (71, 0.9995286141666833),
 (72, 0.9995186346152087),
 (73, 0.9995137294842857),
 (74, 0.9993673414256099),
 (75, 0.9995116654226386),
 (76, 0.999543352577352),
 (77, 0.9995285984455747),
 (78, 0.9995327756400672),
 (79, 0.9995596453724052),
 (80, 0.9993203489756713),
 (81, 0.9995423160108158),
 (82, 0.9995331706926167),
 (83, 0.9995662681937048),
 (84, 0.9995377606036473),
 (85, 0.9995090589889641),
 (86, 0.999513668771824),
 (87, 0.9995900914490432),
 (88, 0.9995513255054326),
 (89, 0.9995104798877924),
 (90, 0.9995200699347501),
 (91, 0.9995475683698818),
 (92, 0.9995632768485333),
 (93, 0.9994137770985175),
 (94, 0.9995362651991244),
 (95, 0.9995741035459492),
 (96, 0.9995839093450438),
 (97, 0.9995444241419339),
 (98, 0.999554934698345),
 (99, 0.9995727502893496),
 (100, 0.9995496156756338),
 (101, 0.9995276710504363),
 (102, 0.9995742650167386),
 (103, 0.9995530024567536),
 (104, 0.9995452568288742),
 (105, 0.999542791693433),
 (106, 0.9995582656730458),
 (107, 0.9995409088337246),
 (108, 0.9995359977636957),
 (109, 0.9995742154828395),
 (110, 0.999549371583477),
 (111, 0.9995229207258369),
 (112, 0.9995637769800526),
 (113, 0.9994925095498721),
 (114, 0.9995705811827352),
 (115, 0.999545670489784),
 (116, 0.9995400135712779),
 (117, 0.999537210208138),
 (118, 0.9995584494965861),
 (119, 0.9995664300373045),
 (120, 0.9995769409915658),
 (121, 0.999537731827215),
 (122, 0.9995764395926761),
 (123, 0.9995380505521506),
 (124, 0.9995137952419954),
 (125, 0.999519042307745),
 (126, 0.9995745964229961),
 (127, 0.9993780571326468),
 (128, 0.9995526794622062),
 (129, 0.9995425396940769),
 (130, 0.9995540644555384),
 (131, 0.9995542473265241),
 (132, 0.9995818207165131),
 (133, 0.9995628177282839),
 (134, 0.9995400653952825),
 (135, 0.9995525121836052),
 (136, 0.9995540564426614),
 (137, 0.9995948137634613),
 (138, 0.9995526906010983),
 (139, 0.9995988280971377),
 (140, 0.9994928020961836),
 (141, 0.9995062171635037),
 (142, 0.9995594219520483),
 (143, 0.9994000385246173),
 (144, 0.9995434687857251),
 (145, 0.9996069287762711),
 (146, 0.9995414035825646),
 (147, 0.9995501280848013),
 (148, 0.9995102613615996),
 (149, 0.999580979229552),
 (150, 0.9995810391707888),
 (151, 0.9996606468565414),
 (152, 0.9995889844572714),
 (153, 0.9995798763687288),
 (154, 0.9995952365619106),
 (155, 0.9996031669417091),
 (156, 0.9995841287203935),
 (157, 0.9995750270979228),
 (158, 0.9995851408523492),
 (159, 0.999630206724235),
 (160, 0.9996465154389652),
 (161, 0.999547968120424),
 (162, 0.9995721710761524),
 (163, 0.9996093048085245),
 (164, 0.999502820993988),
 (165, 0.999583309218912),
 (166, 0.9995870040200617),
 (167, 0.9996618364475958),
 (168, 0.9995993598077437),
 (169, 0.99960001480592),
 (170, 0.9995640680067289),
 (171, 0.9996066579838679),
 (172, 0.9996339239503157),
 (173, 0.9995757240036144),
 (174, 0.9996077909382348),
 (175, 0.9995614854763266),
 (176, 0.9996048758355504),
 (177, 0.9995515852495566),
 (178, 0.9995740716088063),
 (179, 0.999449254424497),
 (180, 0.999573078732354),
 (181, 0.9995374327377615),
 (182, 0.9995206966943609),
 (183, 0.9995338841757618),
 (184, 0.999533376718455),
 (185, 0.9995182559237639),
 (186, 0.9995345724253005),
 (187, 0.9995033507261127),
 (188, 0.9995100485576067),
 (189, 0.9995580714812557),
 (190, 0.9995825489581085),
 (191, 0.9995215431642479),
 (192, 0.999494189038783),
 (193, 0.9995572617250557),
 (194, 0.9995626514802262),
 (195, 0.9995237755027736),
 (196, 0.9995345165593167),
 (197, 0.9995558601729375),
 (198, 0.9995702464038455),
 (199, 0.9995840955436651),
 (200, 0.9995796645000429),
 (201, 0.9995641694056469),
 (202, 0.9995609572697871),
 (203, 0.9996066832135388),
 (204, 0.9995580433191048),
 (205, 0.9995754441588884),
 (206, 0.9995794711490621),
 (207, 0.9995776205469665),
 (208, 0.9995667010516723),
 (209, 0.999565569417491),
 (210, 0.99966241188166),
 (211, 0.9995576190057929),
 (212, 0.9996072373964675),
 (213, 0.9995607904865748),
 (214, 0.9995256539568385),
 (215, 0.9995780655694348),
 (216, 0.9995281313562046),
 (217, 0.9995765343572733),
 (218, 0.9995777141907849),
 (219, 0.9995407657232552),
 (220, 0.9996321192862707),
 (221, 0.9996063614567231),
 (222, 0.9995700246739538),
 (223, 0.9995938580862388),
 (224, 0.9995536151009184),
 (225, 0.9995665267215387),
 (226, 0.9996137305290915),
 (227, 0.999532862469021),
 (228, 0.999557241506616),
 (229, 0.9995499897428296),
 (230, 0.9995575440616763),
 (231, 0.9995420412070433),
 (232, 0.9995623532253498),
 (233, 0.9996174748428422),
 (234, 0.999589861859108),
 (235, 0.9995420319720735),
 (236, 0.9995410484584323),
 (237, 0.9995087472012563),
 (238, 0.9995173297297357),
 (239, 0.9995288251094451),
 (240, 0.9995382931458153),
 (241, 0.9995589902751234),
 (242, 0.9995356080639948),
 (243, 0.9996494332640038),
 (244, 0.9995302417455764),
 (245, 0.9995077281332327),
 (246, 0.9995742903344954),
 (247, 0.9995816763648545),
 (248, 0.9995541280575292),
 (249, 0.9996010296706552),
 (250, 0.9994854851474637),
 (251, 0.999526194538511),
 (252, 0.9995840200315779),
 (253, 0.9995676698302822),
 (254, 0.9995518311689836),
 (255, 0.9995414038309398),
 (256, 0.999516571196531),
 (257, 0.9995589672433594),
 (258, 0.999600439403534),
 (259, 0.9995717063442083),
 (260, 0.9995574159461788),
 (261, 0.999597809609976),
 (262, 0.9995450862264808),
 (263, 0.999552920194863),
 (264, 0.9995506494886389),
 (265, 0.9995173628906626),
 (266, 0.9995798321541297),
 (267, 0.9995775410094566),
 (268, 0.999562924472414),
 (269, 0.9995474699837655),
 (270, 0.9995400956646432),
 (271, 0.9996173791560542),
 (272, 0.9995611832751299),
 (273, 0.9995375018759849),
 (274, 0.9995390191564467),
 (275, 0.9996176362742587),
 (276, 0.9995484343709006),
 (277, 0.9995335262280403),
 (278, 0.9995561111007937),
 (279, 0.9995785388547804),
 (280, 0.9995308550310832),
 (281, 0.9996006053617047),
 (282, 0.999593044929348),
 (283, 0.9995609133531985),
 (284, 0.9995375280150928),
 (285, 0.9995844946103294),
 (286, 0.9996182988996856),
 (287, 0.9995581315425459),
 (288, 0.9995469238818688),
 (289, 0.9995526363380007),
 (290, 0.9995996144644163),
 (291, 0.9995542435702844),
 (292, 0.9995805451157005),
 (293, 0.9995589789154639),
 (294, 0.9995571440876004),
 (295, 0.9995649138659561),
 (296, 0.9995678534325994),
 (297, 0.9995567538915843),
 (298, 0.9995587058568493),
 (299, 0.9995586742009607),
 (300, 0.9996005646726194),
 (301, 0.9995456169153205),
 (302, 0.999571332460895),
 (303, 0.9995780541642015),
 (304, 0.9995588729412805),
 (305, 0.9995509848144221),
 (306, 0.9995824515243535),
 (307, 0.9995580407947874),
 (308, 0.9995593751391297),
 (309, 0.9996113725849942),
 (310, 0.999556731069088),
 (311, 0.9995862939288616),
 (312, 0.9995730483123604),
 (313, 0.9995821942756952),
 (314, 0.9996016087617642),
 (315, 0.9996447461220406),
 (316, 0.9995612767375645),
 (317, 0.9995960212300686),
 (318, 0.9995632710960441),
 (319, 0.9996146728478461),
 (320, 0.9995535768993824),
 (321, 0.9995684208007988),
 (322, 0.9995553550278942),
 (323, 0.9995810491524122),
 (324, 0.9996070594344063),
 (325, 0.999562683686157),
 (326, 0.9995863695351646),
 (327, 0.9996188034479551),
 (328, 0.9995954740898695),
 (329, 0.999578775918871),
 (330, 0.9995829541765292),
 (331, 0.9995655199644627),
 (332, 0.9995581854327412),
 (333, 0.9995828149453153),
 (334, 0.9996376435449496),
 (335, 0.9995642608505927),
 (336, 0.9995558648912536),
 (337, 0.9995508831567708),
 (338, 0.9995720012057814),
 (339, 0.9995844627478918),
 (340, 0.9995691213383684),
 (341, 0.9994858202304668),
 (342, 0.9995505441594075),
 (343, 0.9995922599575371),
 (344, 0.9995749565706968),
 (345, 0.9995688781834284),
 (346, 0.9995541018315894),
 (347, 0.9995904093947338),
 (348, 0.9995651445752431),
 (349, 0.9995893232263071),
 (350, 0.999570222878966),
 (351, 0.9995763083411958),
 (352, 0.9995507861349708),
 (353, 0.9995228241608984),
 (354, 0.9995941535909487),
 (355, 0.9995690889860066),
 (356, 0.9995530395324952),
 (357, 0.9995329457353674),
 (358, 0.9995596290444743),
 (359, 0.999542997440799),
 (360, 0.9995836112784796),
 (361, 0.9995613945805711),
 (362, 0.9995640028198611),
 (363, 0.9995573075361309),
 (364, 0.9995428703867155),
 (365, 0.9995611601180019),
 (366, 0.9995937114876424),
 (367, 0.9995479595724482),
 (368, 0.9995353487119351),
 (369, 0.9995563746611951),
 (370, 0.9995470875570471),
 (371, 0.9995491219085234),
 (372, 0.9995519066270242),
 (373, 0.9995936956365511),
 (374, 0.9995529010153772),
 (375, 0.9995638767014566),
 (376, 0.9995672247115501),
 (377, 0.9995828991418783),
 (378, 0.99959649554254),
 (379, 0.9995610451111786),
 (380, 0.9995777533196754),
 (381, 0.9995678893806385),
 (382, 0.9995744743226453),
 (383, 0.9995756201828039),
 (384, 0.9995640840816417),
 (385, 0.9995702397527807),
 (386, 0.999600010889536),
 (387, 0.9995836716271793),
 (388, 0.9995957858955707),
 (389, 0.9996062962184548),
 (390, 0.9995664878627838),
 (391, 0.999524664692239),
 (392, 0.9995582055728311),
 (393, 0.9995391755128101),
 (394, 0.9995117824490629),
 (395, 0.9995929938718833),
 (396, 0.9995762651301111),
 (397, 0.999544880224533),
 (398, 0.9995884274705521),
 (399, 0.9995660749798125),
 (400, 0.999595793080627),
 (401, 0.9995790133211132),
 (402, 0.9995651142946302),
 (403, 0.9995689947905294),
 (404, 0.9995678281274002),
 (405, 0.9995724562961188),
 (406, 0.9995827249605417),
 (407, 0.9995921923510461),
 (408, 0.99955635684707),
 (409, 0.999559471748932),
 (410, 0.9995719701327596),
 (411, 0.9995709247176675),
 (412, 0.9995926703746096),
 (413, 0.9995530185628456),
 (414, 0.9995746156645186),
 (415, 0.9995711573621655),
 (416, 0.9995747152735699),
 (417, 0.9995676010552347),
 (418, 0.9995642608584875),
 (419, 0.9995546661891639),
 (420, 0.999551855211146),
 (421, 0.9995780162662826),
 (422, 0.9996106984160786),
 (423, 0.9995780004827961),
 (424, 0.9995750552687334),
 (425, 0.9995118650324722),
 (426, 0.9995080426234617),
 (427, 0.9995222140581768),
 (428, 0.9995564132285728),
 (429, 0.9995857420562583),
 (430, 0.9996424259935522),
 (431, 0.9995613861861257),
 (432, 0.999572148984173),
 (433, 0.9995381762588843),
 (434, 0.9995194750678664),
 (435, 0.9995585715094242),
 (436, 0.9995815130523177),
 (437, 0.9995777871781122),
 (438, 0.9995732670030645),
 (439, 0.9995608916177048),
 (440, 0.9995408377283367),
 (441, 0.9995553420479275),
 (442, 0.9995792457319242),
 (443, 0.9995588561672544),
 (444, 0.9995358466227824),
 (445, 0.9995624385696147),
 (446, 0.9995769562756033),
 (447, 0.9995471495211367),
 (448, 0.9995527030075366),
 (449, 0.9995300704852533),
 (450, 0.9995437366295677),
 (451, 0.9994503556275859),
 (452, 0.9995726346284493),
 (453, 0.9995492613661761),
 (454, 0.9995532962433834),
 (455, 0.9995751742779114),
 (456, 0.9995686252469744),
 (457, 0.9996300150508506),
 (458, 0.9995849480550272),
 (459, 0.9995757113981107),
 (460, 0.9995585680506115),
 (461, 0.9995680642121215),
 (462, 0.9995877079849648),
 (463, 0.9995383221721447),
 (464, 0.9995623665748091),
 (465, 0.999569472363746),
 (466, 0.9995796388495457),
 (467, 0.9995695908227035),
 (468, 0.9995632129633857),
 (469, 0.9995628734113619),
 (470, 0.9995685336541259),
 (471, 0.9995386173303882),
 (472, 0.9995976212813903),
 (473, 0.9995686649074355),
 (474, 0.9995485534447018),
 (475, 0.9995721530343811),
 (476, 0.9995630309747132),
 (477, 0.9995648859440328),
 (478, 0.9995358340200752),
 (479, 0.9995503773215222),
 (480, 0.9995635289395336),
 (481, 0.9995848181148467),
 (482, 0.9996061987121025),
 (483, 0.9995718169851218),
 (484, 0.9995352231948041),
 (485, 0.999477693489416),
 (486, 0.9995360401860046),
 (487, 0.9995615195077713),
 (488, 0.9995624284738173),
 (489, 0.9995663886648658),
 (490, 0.9995979918948743),
 (491, 0.9996218152761842),
 (492, 0.9995433734538032),
 (493, 0.9995580627462902),
 (494, 0.9995453951736919),
 (495, 0.9995593431224984),
 (496, 0.9995316622330679),
 (497, 0.999445852694748),
 (498, 0.9995556293855399),
 (499, 0.9995605516324458),
 (500, 0.9996187356516811),
 (501, 0.9995320830103132),
 (502, 0.9995406250376415),
 (503, 0.9995362708830433),
 (504, 0.9995559884850368),
 (505, 0.9995813173350063),
 (506, 0.9995764533114648),
 (507, 0.9995675774186048),
 (508, 0.9995529472817078),
 (509, 0.9995742169695027),
 (510, 0.9995602733419847),
 (511, 0.9995525289453155),
 (512, 0.9995550818168026),
 (513, 0.9996742931528956),
 (514, 0.9995568765406773),
 (515, 0.9995382806532055),
 (516, 0.9996129311100747),
 (517, 0.9995394039679046),
 (518, 0.9995602837235822),
 (519, 0.9995679081339907),
 (520, 0.9995911770480012),
 (521, 0.9995845760656402),
 (522, 0.9995679534625653),
 (523, 0.9995270934638362),
 (524, 0.9995513483382783),
 (525, 0.9995429005967135),
 (526, 0.9995609353145716),
 (527, 0.9995335061494542),
 (528, 0.9995638578837118),
 (529, 0.9995691994431652),
 (530, 0.9995725742929362),
 (531, 0.9995699323164254),
 (532, 0.9995944763231569),
 (533, 0.9995596746186262),
 (534, 0.9995487277330014),
 (535, 0.9995653514089563),
 (536, 0.9995503491962103),
 (537, 0.9995677299825035),
 (538, 0.9995413704140428),
 (539, 0.9995139055381446),
 (540, 0.9995450397887689),
 (541, 0.9995721589396244),
 (542, 0.9995531518454567),
 (543, 0.9995946459472596),
 (544, 0.9995620337771015),
 (545, 0.9995657240701881),
 (546, 0.999554157007705),
 (547, 0.9996036197391901),
 (548, 0.999552407614364),
 (549, 0.9995609391649969),
 (550, 0.999555487545861),
 (551, 0.9995641223346421),
 (552, 0.9995804657791201),
 (553, 0.9995310379070406),
 (554, 0.9995553069629984),
 (555, 0.9995595726565559),
 (556, 0.9995604229652657),
 (557, 0.9995189366883793),
 (558, 0.9995569928055262),
 (559, 0.9995702791125899),
 (560, 0.9995523024318338),
 (561, 0.9995703455385851),
 (562, 0.9995172131070801),
 (563, 0.9995414443775724),
 (564, 0.999552051394724),
 (565, 0.9995538488823654),
 (566, 0.9995603705819494),
 (567, 0.9995548984787995),
 (568, 0.9995386459670221),
 (569, 0.9995776677581503),
 (570, 0.9995779960017483),
 (571, 0.9995539790120784),
 (572, 0.9995197055953351),
 (573, 0.9995448525984977),
 (574, 0.9995393725902255),
 (575, 0.999554041485608),
 (576, 0.9995653770143039),
 (577, 0.9996124082230917),
 (578, 0.9995577729701396),
 (579, 0.9995324523582072),
 (580, 0.9995583762966992),
 (581, 0.9995582217367255),
 (582, 0.9995485428580598),
 (583, 0.9995620332991026),
 (584, 0.9995401339971267),
 (585, 0.9995803878599067),
 (586, 0.9995669773192646),
 (587, 0.9995371931154065),
 (588, 0.9995426722364494),
 (589, 0.9995582264583748),
 (590, 0.9995572131458611),
 (591, 0.9995490758389266),
 (592, 0.9995700140088029),
 (593, 0.9995178624061215),
 (594, 0.9995325719412542),
 (595, 0.9996127158069885),
 (596, 0.9995729219133731),
 (597, 0.9995830620808392),
 (598, 0.9995237650023225),
 (599, 0.9995388638029374),
 (600, 0.9995277592681175),
 (601, 0.9995288732432982),
 (602, 0.9995356767297072),
 (603, 0.9995408319911326),
 (604, 0.9995488419485729),
 (605, 0.9996004469781241),
 (606, 0.9995224166883225),
 (607, 0.9995866145614191),
 (608, 0.9995493429269077),
 (609, 0.9995846255092581),
 (610, 0.9995562890408647),
 (611, 0.9995801406042617),
 (612, 0.9995754579619165),
 (613, 0.99955440253103),
 (614, 0.999576075669725),
 (615, 0.9995557670992701),
 (616, 0.9995590850036526),
 (617, 0.9995380402745697),
 (618, 0.9995601158348132),
 (619, 0.9995487916523774),
 (620, 0.9995707483449574),
 (621, 0.9995217994644565),
 (622, 0.9995164193768096),
 (623, 0.9995304616801919),
 (624, 0.9995331598686794),
 (625, 0.9995339918779448),
 (626, 0.9995270540912142),
 (627, 0.9994957542478982),
 (628, 0.9995655107721116),
 (629, 0.9995571190594104),
 (630, 0.9995998105226833),
 (631, 0.9995536190823013),
 (632, 0.9995316030253292),
 (633, 0.999565539603059),
 (634, 0.9995674927319154),
 (635, 0.9995289758478395),
 (636, 0.9995509232810404),
 (637, 0.9995800600913095),
 (638, 0.9995285244776138),
 (639, 0.9995369537866021),
 (640, 0.9995493320814085),
 (641, 0.9995302354666759),
 (642, 0.9995678267857349),
 (643, 0.9995590347308583),
 (644, 0.9995484574057567),
 (645, 0.9995384348305035),
 (646, 0.9995225651150607),
 (647, 0.9995443547978906),
 (648, 0.9995153505961315),
 (649, 0.9995505857653361),
 (650, 0.9995438132467002),
 (651, 0.9995445352043395),
 (652, 0.9995872113432398),
 (653, 0.999564684689659),
 (654, 0.9995799330054994),
 (655, 0.9995756952770682),
 (656, 0.9995639718230153),
 (657, 0.9995489900879356),
 (658, 0.9995406651785989),
 (659, 0.9995473237490722),
 (660, 0.9995593189436212),
 (661, 0.9995376700465455),
 (662, 0.9995453804718247),
 (663, 0.9996018067135045),
 (664, 0.9995279532836147),
 (665, 0.9995261162969098),
 (666, 0.9995420374854994),
 (667, 0.9995291341565596),
 (668, 0.9995417675373897),
 (669, 0.9995750828614619),
 (670, 0.9995515342484944),
 (671, 0.9995521723078136),
 (672, 0.9995377958904246),
 (673, 0.9995627138826608),
 (674, 0.9995428587253027),
 (675, 0.9995549042174765),
 (676, 0.9995341081251403),
 (677, 0.9995654200034075),
 (678, 0.9995427328641845),
 (679, 0.9995140465521805),
 (680, 0.9995642686184593),
 (681, 0.9995573932932228),
 (682, 0.9995674571618488),
 (683, 0.999514963311366),
 (684, 0.9995590731632248),
 (685, 0.9995269586003436),
 (686, 0.9995165301522989),
 (687, 0.9995363112677584),
 (688, 0.9995259872253035),
 (689, 0.999532132144408),
 (690, 0.9995321016187955),
 (691, 0.9995590124044059),
 (692, 0.999553334685344),
 (693, 0.9995305771781696),
 (694, 0.999552287392028),
 (695, 0.9995603361604513),
 (696, 0.9995362617411916),
 (697, 0.9995550310135997),
 (698, 0.9995386283907252),
 (699, 0.9995328774888602),
 (700, 0.999558265112528),
 (701, 0.9995461770880603),
 (702, 0.9995491639098484),
 (703, 0.9994756728111974),
 (704, 0.9995384625775743),
 (705, 0.9995337343116191),
 (706, 0.999552408969366),
 (707, 0.999552803084699),
 (708, 0.9995560911642242),
 (709, 0.9995191517372319),
 (710, 0.9995260154668614),
 (711, 0.9995188961452783),
 (712, 0.9995394622319749),
 (713, 0.9995391168806153),
 (714, 0.9995715655541048),
 (715, 0.9995440305218866),
 (716, 0.9995254347808644),
 (717, 0.999545308494871),
 (718, 0.9995450644269324),
 (719, 0.9995364791499578),
 (720, 0.9995520350765403),

In [538]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 0.9999999999999999),
 (513, 0.9996742931528956),
 (210, 0.99966241188166),
 (167, 0.9996618364475958),
 (151, 0.9996606468565414),
 (243, 0.9996494332640038),
 (160, 0.9996465154389652),
 (315, 0.9996447461220406),
 (430, 0.9996424259935522),
 (334, 0.9996376435449496),
 (172, 0.9996339239503157),
 (220, 0.9996321192862707),
 (159, 0.999630206724235),
 (457, 0.9996300150508506),
 (491, 0.9996218152761842),
 (31, 0.999619025043171),
 (327, 0.9996188034479551),
 (500, 0.9996187356516811),
 (286, 0.9996182988996856),
 (275, 0.9996176362742587),
 (233, 0.9996174748428422),
 (271, 0.9996173791560542),
 (319, 0.9996146728478461),
 (226, 0.9996137305290915),
 (516, 0.9996129311100747),
 (595, 0.9996127158069885),
 (577, 0.9996124082230917),
 (309, 0.9996113725849942),
 (422, 0.9996106984160786),
 (163, 0.9996093048085245),
 (174, 0.9996077909382348),
 (212, 0.9996072373964675),
 (324, 0.9996070594344063),
 (145, 0.9996069287762711),
 (203, 0.9996066832135388),
 (171, 0.9996066579838679),
 (221, 0.9996063614567231),
 (389, 0.9996062962184548),
 (482, 0.9996061987121025),
 (176, 0.9996048758355504),
 (547, 0.9996036197391901),
 (155, 0.9996031669417091),
 (663, 0.9996018067135045),
 (314, 0.9996016087617642),
 (249, 0.9996010296706552),
 (281, 0.9996006053617047),
 (300, 0.9996005646726194),
 (605, 0.9996004469781241),
 (258, 0.999600439403534),
 (169, 0.99960001480592),
 (386, 0.999600010889536),
 (630, 0.9995998105226833),
 (290, 0.9995996144644163),
 (168, 0.9995993598077437),
 (139, 0.9995988280971377),
 (490, 0.9995979918948743),
 (261, 0.999597809609976),
 (472, 0.9995976212813903),
 (378, 0.99959649554254),
 (36, 0.9995962799488355),
 (317, 0.9995960212300686),
 (400, 0.999595793080627),
 (388, 0.9995957858955707),
 (328, 0.9995954740898695),
 (154, 0.9995952365619106),
 (137, 0.9995948137634613),
 (543, 0.9995946459472596),
 (532, 0.9995944763231569),
 (354, 0.9995941535909487),
 (223, 0.9995938580862388),
 (366, 0.9995937114876424),
 (373, 0.9995936956365511),
 (282, 0.999593044929348),
 (395, 0.9995929938718833),
 (3, 0.9995927613974778),
 (412, 0.9995926703746096),
 (343, 0.9995922599575371),
 (407, 0.9995921923510461),
 (1, 0.9995916341242957),
 (520, 0.9995911770480012),
 (18, 0.99959114344946),
 (347, 0.9995904093947338),
 (87, 0.9995900914490432),
 (234, 0.999589861859108),
 (349, 0.9995893232263071),
 (152, 0.9995889844572714),
 (30, 0.9995886671001932),
 (398, 0.9995884274705521),
 (5, 0.9995882725696232),
 (462, 0.9995877079849648),
 (652, 0.9995872113432398),
 (166, 0.9995870040200617),
 (607, 0.9995866145614191),
 (326, 0.9995863695351646),
 (311, 0.9995862939288616),
 (429, 0.9995857420562583),
 (158, 0.9995851408523492),
 (2, 0.9995850079389759),
 (458, 0.9995849480550272),
 (481, 0.9995848181148467),
 (609, 0.9995846255092581),
 (521, 0.9995845760656402),
 (285, 0.9995844946103294),
 (339, 0.9995844627478918),
 (29, 0.9995843149489536),
 (156, 0.9995841287203935),
 (199, 0.9995840955436651),
 (252, 0.9995840200315779),
 (96, 0.9995839093450438),
 (387, 0.9995836716271793),
 (360, 0.9995836112784796),
 (165, 0.999583309218912),
 (597, 0.9995830620808392),
 (330, 0.9995829541765292),
 (377, 0.9995828991418783),
 (333, 0.9995828149453153),
 (406, 0.9995827249605417),
 (190, 0.9995825489581085),
 (306, 0.9995824515243535),
 (313, 0.9995821942756952),
 (132, 0.9995818207165131),
 (247, 0.9995816763648545),
 (436, 0.9995815130523177),
 (505, 0.9995813173350063),
 (65, 0.9995811703402167),
 (323, 0.9995810491524122),
 (150, 0.9995810391707888),
 (149, 0.999580979229552),
 (292, 0.9995805451157005),
 (552, 0.9995804657791201),
 (585, 0.9995803878599067),
 (611, 0.9995801406042617),
 (637, 0.9995800600913095),
 (654, 0.9995799330054994),
 (153, 0.9995798763687288),
 (266, 0.9995798321541297),
 (200, 0.9995796645000429),
 (466, 0.9995796388495457),
 (20, 0.9995796134739942),
 (206, 0.9995794711490621),
 (442, 0.9995792457319242),
 (401, 0.9995790133211132),
 (329, 0.999578775918871),
 (279, 0.9995785388547804),
 (215, 0.9995780655694348),
 (303, 0.9995780541642015),
 (421, 0.9995780162662826),
 (423, 0.9995780004827961),
 (570, 0.9995779960017483),
 (437, 0.9995777871781122),
 (380, 0.9995777533196754),
 (32, 0.9995777341272125),
 (218, 0.9995777141907849),
 (569, 0.9995776677581503),
 (207, 0.9995776205469665),
 (267, 0.9995775410094566),
 (28, 0.9995775148280353),
 (446, 0.9995769562756033),
 (120, 0.9995769409915658),
 (217, 0.9995765343572733),
 (506, 0.9995764533114648),
 (122, 0.9995764395926761),
 (351, 0.9995763083411958),
 (396, 0.9995762651301111),
 (614, 0.999576075669725),
 (173, 0.9995757240036144),
 (459, 0.9995757113981107),
 (655, 0.9995756952770682),
 (383, 0.9995756201828039),
 (612, 0.9995754579619165),
 (205, 0.9995754441588884),
 (455, 0.9995751742779114),
 (669, 0.9995750828614619),
 (424, 0.9995750552687334),
 (157, 0.9995750270979228),
 (344, 0.9995749565706968),
 (416, 0.9995747152735699),
 (414, 0.9995746156645186),
 (126, 0.9995745964229961),
 (382, 0.9995744743226453),
 (246, 0.9995742903344954),
 (102, 0.9995742650167386),
 (509, 0.9995742169695027),
 (109, 0.9995742154828395),
 (95, 0.9995741035459492),
 (178, 0.9995740716088063),
 (56, 0.9995738874321667),
 (438, 0.9995732670030645),
 (180, 0.999573078732354),
 (312, 0.9995730483123604),
 (596, 0.9995729219133731),
 (99, 0.9995727502893496),
 (452, 0.9995726346284493),
 (530, 0.9995725742929362),
 (9, 0.9995724651709197),
 (405, 0.9995724562961188),
 (162, 0.9995721710761524),
 (541, 0.9995721589396244),
 (475, 0.9995721530343811),
 (432, 0.999572148984173),
 (338, 0.9995720012057814),
 (410, 0.9995719701327596),
 (483, 0.9995718169851218),
 (259, 0.9995717063442083),
 (35, 0.9995716987270762),
 (714, 0.9995715655541048),
 (54, 0.9995714528234372),
 (302, 0.999571332460895),
 (415, 0.9995711573621655),
 (411, 0.9995709247176675),
 (620, 0.9995707483449574),
 (114, 0.9995705811827352),
 (561, 0.9995703455385851),
 (59, 0.9995702808050446),
 (559, 0.9995702791125899),
 (198, 0.9995702464038455),
 (385, 0.9995702397527807),
 (53, 0.9995702229943747),
 (350, 0.999570222878966),
 (222, 0.9995700246739538),
 (592, 0.9995700140088029),
 (531, 0.9995699323164254),
 (50, 0.9995698776315879),
 (467, 0.9995695908227035),
 (465, 0.999569472363746),
 (26, 0.9995692810997423),
 (529, 0.9995691994431652),
 (27, 0.9995691232720872),
 (340, 0.9995691213383684),
 (355, 0.9995690889860066),
 (403, 0.9995689947905294),
 (345, 0.9995688781834284),
 (473, 0.9995686649074355),
 (456, 0.9995686252469744),
 (470, 0.9995685336541259),
 (321, 0.9995684208007988),
 (461, 0.9995680642121215),
 (522, 0.9995679534625653),
 (519, 0.9995679081339907),
 (381, 0.9995678893806385),
 (296, 0.9995678534325994),
 (404, 0.9995678281274002),
 (642, 0.9995678267857349),
 (24, 0.9995677433154537),
 (537, 0.9995677299825035),
 (253, 0.9995676698302822),
 (417, 0.9995676010552347),
 (507, 0.9995675774186048),
 (634, 0.9995674927319154),
 (55, 0.9995674915638426),
 (682, 0.9995674571618488),
 (376, 0.9995672247115501),
 (586, 0.9995669773192646),
 (208, 0.9995667010516723),
 (225, 0.9995665267215387),
 (390, 0.9995664878627838),
 (14, 0.9995664327668942),
 (119, 0.9995664300373045),
 (10, 0.9995663947088358),
 (489, 0.9995663886648658),
 (83, 0.9995662681937048),
 (399, 0.9995660749798125),
 (19, 0.9995658400944066),
 (545, 0.9995657240701881),
 (209, 0.999565569417491),
 (633, 0.999565539603059),
 (331, 0.9995655199644627),
 (628, 0.9995655107721116),
 (677, 0.9995654200034075),
 (576, 0.9995653770143039),
 (535, 0.9995653514089563),
 (348, 0.9995651445752431),
 (402, 0.9995651142946302),
 (295, 0.9995649138659561),
 (477, 0.9995648859440328),
 (653, 0.999564684689659),
 (21, 0.9995643839951337),
 (680, 0.9995642686184593),
 (418, 0.9995642608584875),
 (335, 0.9995642608505927),
 (201, 0.9995641694056469),
 (551, 0.9995641223346421),
 (384, 0.9995640840816417),
 (170, 0.9995640680067289),
 (362, 0.9995640028198611),
 (656, 0.9995639718230153),
 (375, 0.9995638767014566),
 (528, 0.9995638578837118),
 (112, 0.9995637769800526),
 (480, 0.9995635289395336),
 (92, 0.9995632768485333),
 (318, 0.9995632710960441),
 (468, 0.9995632129633857),
 (476, 0.9995630309747132),
 (268, 0.999562924472414),
 (469, 0.9995628734113619),
 (133, 0.9995628177282839),
 (673, 0.9995627138826608),
 (325, 0.999562683686157),
 (46, 0.999562658188014),
 (194, 0.9995626514802262),
 (445, 0.9995624385696147),
 (488, 0.9995624284738173),
 (464, 0.9995623665748091),
 (232, 0.9995623532253498),
 (544, 0.9995620337771015),
 (583, 0.9995620332991026),
 (41, 0.9995616228165167),
 (487, 0.9995615195077713),
 (175, 0.9995614854763266),
 (361, 0.9995613945805711),
 (431, 0.9995613861861257),
 (316, 0.9995612767375645),
 (272, 0.9995611832751299),
 (365, 0.9995611601180019),
 (379, 0.9995610451111786),
 (202, 0.9995609572697871),
 (549, 0.9995609391649969),
 (526, 0.9995609353145716),
 (283, 0.9995609133531985),
 (439, 0.9995608916177048),
 (213, 0.9995607904865748),
 (499, 0.9995605516324458),
 (556, 0.9995604229652657),
 (566, 0.9995603705819494),
 (695, 0.9995603361604513),
 (518, 0.9995602837235822),
 (510, 0.9995602733419847),
 (618, 0.9995601158348132),
 (533, 0.9995596746186262),
 (79, 0.9995596453724052),
 (358, 0.9995596290444743),
 (555, 0.9995595726565559),
 (409, 0.999559471748932),
 (142, 0.9995594219520483),
 (308, 0.9995593751391297),
 (495, 0.9995593431224984),
 (660, 0.9995593189436212),
 (49, 0.9995592993247073),
 (616, 0.9995590850036526),
 (684, 0.9995590731632248),
 (643, 0.9995590347308583),
 (691, 0.9995590124044059),
 (241, 0.9995589902751234),
 (293, 0.9995589789154639),
 (257, 0.9995589672433594),
 (304, 0.9995588729412805),
 (443, 0.9995588561672544),
 (44, 0.9995587671379366),
 (298, 0.9995587058568493),
 (299, 0.9995586742009607),
 (435, 0.9995585715094242),
 (460, 0.9995585680506115),
 (118, 0.9995584494965861),
 (580, 0.9995583762966992),
 (106, 0.9995582656730458),
 (700, 0.999558265112528),
 (589, 0.9995582264583748),
 (581, 0.9995582217367255),
 (392, 0.9995582055728311),
 (332, 0.9995581854327412),
 (287, 0.9995581315425459),
 (189, 0.9995580714812557),
 (493, 0.9995580627462902),
 (204, 0.9995580433191048),
 (307, 0.9995580407947874),
 (578, 0.9995577729701396),
 (211, 0.9995576190057929),
 (230, 0.9995575440616763),
 (260, 0.9995574159461788),
 (681, 0.9995573932932228),
 (363, 0.9995573075361309),
 (193, 0.9995572617250557),
 (228, 0.999557241506616),
 (590, 0.9995572131458611),
 (294, 0.9995571440876004),
 (629, 0.9995571190594104),
 (558, 0.9995569928055262),
 (514, 0.9995568765406773),
 (60, 0.9995568037693966),
 (297, 0.9995567538915843),
 (310, 0.999556731069088),
 (428, 0.9995564132285728),
 (369, 0.9995563746611951),
 (408, 0.99955635684707),
 (610, 0.9995562890408647),
 (278, 0.9995561111007937),
 (708, 0.9995560911642242),
 (504, 0.9995559884850368),
 (336, 0.9995558648912536),
 (197, 0.9995558601729375),
 (615, 0.9995557670992701),
 (498, 0.9995556293855399),
 (57, 0.9995555630821046),
 (550, 0.999555487545861),
 (322, 0.9995553550278942),
 (441, 0.9995553420479275),
 (554, 0.9995553069629984),
 (512, 0.9995550818168026),
 (697, 0.9995550310135997),
 (98, 0.999554934698345),
 (675, 0.9995549042174765),
 (567, 0.9995548984787995),
 (419, 0.9995546661891639),
 (613, 0.99955440253103),
 (131, 0.9995542473265241),
 (291, 0.9995542435702844),
 (546, 0.999554157007705),
 (248, 0.9995541280575292),
 (346, 0.9995541018315894),
 (130, 0.9995540644555384),
 (136, 0.9995540564426614),
 (575, 0.999554041485608),
 (571, 0.9995539790120784),
 (565, 0.9995538488823654),
 (631, 0.9995536190823013),
 (224, 0.9995536151009184),
 (320, 0.9995535768993824),
 (692, 0.999553334685344),
 (454, 0.9995532962433834),
 (542, 0.9995531518454567),
 (356, 0.9995530395324952),
 (413, 0.9995530185628456),
 (103, 0.9995530024567536),
 (4, 0.99955298375433),
 (508, 0.9995529472817078),
 (263, 0.999552920194863),
 (374, 0.9995529010153772),
 (707, 0.999552803084699),
 (448, 0.9995527030075366),
 (138, 0.9995526906010983),
 (128, 0.9995526794622062),
 (289, 0.9995526363380007),
 (511, 0.9995525289453155),
 (135, 0.9995525121836052),
 (706, 0.999552408969366),
 (548, 0.999552407614364),
 (560, 0.9995523024318338),
 (694, 0.999552287392028),
 (671, 0.9995521723078136),
 (564, 0.999552051394724),
 (720, 0.9995520350765403),
 (372, 0.9995519066270242),
 (420, 0.999551855211146),
 (254, 0.9995518311689836),
 (177, 0.9995515852495566),
 (670, 0.9995515342484944),
 (524, 0.9995513483382783),
 (88, 0.9995513255054326),
 (305, 0.9995509848144221),
 (636, 0.9995509232810404),
 (337, 0.9995508831567708),
 (352, 0.9995507861349708),
 (264, 0.9995506494886389),
 (649, 0.9995505857653361),
 (342, 0.9995505441594075),
 (37, 0.9995505441318273),
 (479, 0.9995503773215222),
 (536, 0.9995503491962103),
 (147, 0.9995501280848013),
 (63, 0.9995499926317171),
 (229, 0.9995499897428296),
 (100, 0.9995496156756338),
 (110, 0.999549371583477),
 (608, 0.9995493429269077),
 (640, 0.9995493320814085),
 (453, 0.9995492613661761),
 (702, 0.9995491639098484),
 (40, 0.9995491434626457),
 (371, 0.9995491219085234),
 (591, 0.9995490758389266),
 (45, 0.9995490602254395),
 (657, 0.9995489900879356),
 (604, 0.9995488419485729),
 (619, 0.9995487916523774),
 (534, 0.9995487277330014),
 (47, 0.9995485627157548),
 (474, 0.9995485534447018),
 (582, 0.9995485428580598),
 (644, 0.9995484574057567),
 (276, 0.9995484343709006),
 (161, 0.999547968120424),
 (367, 0.9995479595724482),
 (39, 0.9995477504137966),
 (91, 0.9995475683698818),
 (269, 0.9995474699837655),
 (15, 0.9995473737235012),
 (659, 0.9995473237490722),
 (13, 0.9995471501933031),
 (447, 0.9995471495211367),
 (370, 0.9995470875570471),
 (16, 0.9995469311331923),
 (288, 0.9995469238818688),
 (6, 0.9995464198920769),
 (701, 0.9995461770880603),
 (115, 0.999545670489784),
 (301, 0.9995456169153205),
 (494, 0.9995453951736919),
 (662, 0.9995453804718247),
 (717, 0.999545308494871),
 (104, 0.9995452568288742),
 (262, 0.9995450862264808),
 (718, 0.9995450644269324),
 (540, 0.9995450397887689),
 (397, 0.999544880224533),
 (573, 0.9995448525984977),
 (7, 0.9995448373262572),
 (651, 0.9995445352043395),
 (97, 0.9995444241419339),
 (647, 0.9995443547978906),
 (715, 0.9995440305218866),
 (650, 0.9995438132467002),
 (450, 0.9995437366295677),
 (42, 0.9995436349769321),
 (144, 0.9995434687857251),
 (492, 0.9995433734538032),
 (76, 0.999543352577352),
 (359, 0.999542997440799),
 (525, 0.9995429005967135),
 (364, 0.9995428703867155),
 (674, 0.9995428587253027),
 (105, 0.999542791693433),
 (678, 0.9995427328641845),
 (588, 0.9995426722364494),
 (129, 0.9995425396940769),
 (81, 0.9995423160108158),
 (48, 0.9995422852697113),
 (12, 0.9995421914661081),
 (231, 0.9995420412070433),
 (666, 0.9995420374854994),
 (235, 0.9995420319720735),
 (668, 0.9995417675373897),
 (563, 0.9995414443775724),
 (255, 0.9995414038309398),
 (146, 0.9995414035825646),
 (538, 0.9995413704140428),
 (236, 0.9995410484584323),
 (107, 0.9995409088337246),
 (440, 0.9995408377283367),
 (603, 0.9995408319911326),
 (22, 0.9995408096843862),
 (219, 0.9995407657232552),
 (658, 0.9995406651785989),
 (502, 0.9995406250376415),
 (724, 0.9995402841381532),
 (11, 0.9995402577516243),
 (584, 0.9995401339971267),
 (270, 0.9995400956646432),
 (134, 0.9995400653952825),
 (116, 0.9995400135712779),
 (61, 0.9995399946176144),
 (712, 0.9995394622319749),
 (517, 0.9995394039679046),
 (574, 0.9995393725902255),
 (393, 0.9995391755128101),
 (713, 0.9995391168806153),
 (274, 0.9995390191564467),
 (599, 0.9995388638029374),
 (568, 0.9995386459670221),
 (698, 0.9995386283907252),
 (471, 0.9995386173303882),
 (704, 0.9995384625775743),
 (645, 0.9995384348305035),
 (463, 0.9995383221721447),
 (240, 0.9995382931458153),
 (515, 0.9995382806532055),
 (433, 0.9995381762588843),
 (123, 0.9995380505521506),
 (617, 0.9995380402745697),
 (672, 0.9995377958904246),
 (84, 0.9995377606036473),
 (121, 0.999537731827215),
 (661, 0.9995376700465455),
 (284, 0.9995375280150928),
 (273, 0.9995375018759849),
 (181, 0.9995374327377615),
 (117, 0.999537210208138),
 (587, 0.9995371931154065),
 (639, 0.9995369537866021),
 (719, 0.9995364791499578),
 (687, 0.9995363112677584),
 (503, 0.9995362708830433),
 (94, 0.9995362651991244),
 (696, 0.9995362617411916),
 (486, 0.9995360401860046),
 (108, 0.9995359977636957),
 (444, 0.9995358466227824),
 (478, 0.9995358340200752),
 (602, 0.9995356767297072),
 (242, 0.9995356080639948),
 (368, 0.9995353487119351),
 (484, 0.9995352231948041),
 (186, 0.9995345724253005),
 (196, 0.9995345165593167),
 (52, 0.9995345001972965),
 (725, 0.9995341762299083),
 (676, 0.9995341081251403),
 (625, 0.9995339918779448),
 (51, 0.9995339121305692),
 (183, 0.9995338841757618),
 (705, 0.9995337343116191),
 (277, 0.9995335262280403),
 (527, 0.9995335061494542),
 (184, 0.999533376718455),
 (82, 0.9995331706926167),
 (624, 0.9995331598686794),
 (58, 0.9995330847129063),
 (357, 0.9995329457353674),
 (699, 0.9995328774888602),
 (227, 0.999532862469021),
 (78, 0.9995327756400672),
 (594, 0.9995325719412542),
 (579, 0.9995324523582072),
 (8, 0.9995321576154007),
 (689, 0.999532132144408),
 (690, 0.9995321016187955),
 (501, 0.9995320830103132),
 (38, 0.9995319772733751),
 (496, 0.9995316622330679),
 (632, 0.9995316030253292),
 (553, 0.9995310379070406),
 (70, 0.9995309161405174),
 (280, 0.9995308550310832),
 (64, 0.999530646064675),
 (693, 0.9995305771781696),
 (623, 0.9995304616801919),
 (244, 0.9995302417455764),
 (641, 0.9995302354666759),
 (449, 0.9995300704852533),
 (667, 0.9995291341565596),
 (635, 0.9995289758478395),
 (601, 0.9995288732432982),
 (239, 0.9995288251094451),
 (71, 0.9995286141666833),
 (77, 0.9995285984455747),
 (638, 0.9995285244776138),
 (216, 0.9995281313562046),
 (664, 0.9995279532836147),
 (600, 0.9995277592681175),
 (101, 0.9995276710504363),
 (523, 0.9995270934638362),
 (626, 0.9995270540912142),
 (685, 0.9995269586003436),
 (723, 0.9995266044911003),
 (251, 0.999526194538511),
 (665, 0.9995261162969098),
 (710, 0.9995260154668614),
 (688, 0.9995259872253035),
 (214, 0.9995256539568385),
 (716, 0.9995254347808644),
 (68, 0.9995249564326684),
 (391, 0.999524664692239),
 (195, 0.9995237755027736),
 (598, 0.9995237650023225),
 (726, 0.9995236021260029),
 (111, 0.9995229207258369),
 (353, 0.9995228241608984),
 (646, 0.9995225651150607),
 (606, 0.9995224166883225),
 (427, 0.9995222140581768),
 (621, 0.9995217994644565),
 (191, 0.9995215431642479),
 (182, 0.9995206966943609),
 (90, 0.9995200699347501),
 (67, 0.9995199329811393),
 (572, 0.9995197055953351),
 (434, 0.9995194750678664),
 (709, 0.9995191517372319),
 (125, 0.999519042307745),
 (557, 0.9995189366883793),
 (711, 0.9995188961452783),
 (72, 0.9995186346152087),
 (185, 0.9995182559237639),
 (593, 0.9995178624061215),
 (265, 0.9995173628906626),
 (238, 0.9995173297297357),
 (562, 0.9995172131070801),
 (256, 0.999516571196531),
 (686, 0.9995165301522989),
 (622, 0.9995164193768096),
 (721, 0.9995157512047892),
 (17, 0.9995156363042926),
 (648, 0.9995153505961315),
 (683, 0.999514963311366),
 (679, 0.9995140465521805),
 (539, 0.9995139055381446),
 (124, 0.9995137952419954),
 (73, 0.9995137294842857),
 (86, 0.999513668771824),
 (66, 0.9995134761904751),
 (425, 0.9995118650324722),
 (394, 0.9995117824490629),
 (75, 0.9995116654226386),
 (89, 0.9995104798877924),
 (148, 0.9995102613615996),
 (188, 0.9995100485576067),
 (85, 0.9995090589889641),
 (237, 0.9995087472012563),
 (69, 0.9995083715359891),
 (426, 0.9995080426234617),
 (62, 0.9995079873865813),
 (245, 0.9995077281332327),
 (34, 0.9995075163797479),
 (727, 0.9995067970612014),
 (141, 0.9995062171635037),
 (23, 0.9995036562603513),
 (187, 0.9995033507261127),
 (164, 0.999502820993988),
 (627, 0.9994957542478982),
 (33, 0.9994955255715002),
 (192, 0.999494189038783),
 (140, 0.9994928020961836),
 (113, 0.9994925095498721),
 (341, 0.9994858202304668),
 (250, 0.9994854851474637),
 (25, 0.9994837306660652),
 (43, 0.9994826388870599),
 (485, 0.999477693489416),
 (703, 0.9994756728111974),
 (722, 0.9994747832981659),

In [539]:
genres_df

,movieId,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
0,1,0,0,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1995
232,2,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1995
324,3,0,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,0,1995
382,4,0,0,0,0,0,1,0,0,1,...,0,0,0,0,1,0,0,0,0,1995
393,5,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105332,146684,0,0,0,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105333,146878,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1966
105334,148238,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105335,148626,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,2015
105338,149532,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015

In [540]:
df

,movieId,title,userId,rating,timestamp,(no genres listed),Action,Adventure,Animation,Children,...,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western,year
0,1,Toy Story,2,5.0,859046895,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
1,1,Toy Story,5,4.0,1303501039,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
2,1,Toy Story,8,5.0,858610933,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
3,1,Toy Story,11,4.0,850815810,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
4,1,Toy Story,14,4.0,851766286,0,0,1,1,1,...,0,0,0,0,0,0,0,0,0,1995
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105334,148238,A Very Murray Christmas,475,3.0,1451213043,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105335,148626,The Big Short,458,4.0,1452014749,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105336,148626,The Big Short,576,4.5,1451687664,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105337,148626,The Big Short,668,4.5,1451148148,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015
105338,149532,Marco Polo: One Hundred Eyes,475,4.0,1451223429,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2015

In [541]:
vector

userId,1,2,3,4,5,6,7,8,9,10,...,659,660,661,662,663,664,665,666,667,668
movieId,,,,,,,,,,,,,,,,,,,,,
1,0.0,5.0,0.0,0.0,4.0,0.0,0.0,5.0,0.0,0.0,...,0.0,0.0,4.0,5.0,3.0,0.0,0.0,0.0,0.0,3.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,3.0
3,0.0,2.0,0.0,0.0,0.0,0.0,0.0,4.0,3.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
5,0.0,3.0,3.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,...,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,2.5
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,...,2.5,0.0,4.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81845,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0
89745,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
91529,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
99114,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.5
109487,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [542]:
vector.index

Int64Index([     1,      2,      3,      5,      6,      7,     10,     11,
                16,     17,
            ...
             71535,  72998,  73017,  74458,  79132,  81845,  89745,  91529,
             99114, 109487],
           dtype='int64', name='movieId', length=728)

In [586]:
def recommend(movie):
    movie_id = df.loc[df['title']==movie,'movieId'].unique()
    # print(movie_id)
    for i in movie_id:
        if i in vector.index:
            row_number=vector.index.get_loc(i)
            print(row_number)
            break


    # print(row_number)

    # row_number=vector.index.get_loc(movie_id)
    # print(row_number)
    distances=similarity[row_number]
    recommended_movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:11]


    for i in recommended_movie_list:
    #     # print(i[0])
        new_movie_id= vector.index[i[0]]
        # print(new_movie_id)
        
        print(df.loc[df['movieId']==new_movie_id,'title'].iloc[0])

In [587]:
recommend('Avengers, The')

724
Dark Knight Rises, The
X-Men: The Last Stand
Sherlock Holmes
Hellboy
Pirates of the Caribbean: At World's End
Star Trek
Fast and the Furious, The
Serenity
Watchmen
Men in Black II (a.k.a. MIIB) (a.k.a. MIB 2)

In [588]:
movies_list=[]
for ind in vector.index:
    
    p=df.loc[df['movieId']==ind,'title'].iloc[0]
    
    # dummy=df.loc[df['title']==p,'movieId'].iloc[0]
    # print(ind,"-> ",p," -> ",dummy)
    # if dummy != ind:
    #     print(dummy," ",ind," ",p)
    # print(p)
    # movies_list.append([p,ind])
    movies_list.append(p)
    # print(ind)
    # break
movies_list

['Toy Story',
 'Jumanji',
 'Grumpier Old Men',
 'Father of the Bride Part II',
 'Heat',
 'Sabrina',
 'GoldenEye',
 'American President, The',
 'Casino',
 'Sense and Sensibility',
 'Ace Ventura: When Nature Calls',
 'Get Shorty',
 'Copycat',
 'Powder',
 'Leaving Las Vegas',
 'City of Lost Children, The (Cité des enfants perdus, La)',
 'Dangerous Minds',
 'Twelve Monkeys (a.k.a. 12 Monkeys)',
 'Babe',
 'Dead Man Walking',
 'Clueless',
 'Mortal Kombat',
 'To Die For',
 'Seven (a.k.a. Se7en)',
 'Pocahontas',
 'Usual Suspects, The',
 'Mighty Aphrodite',
 'Postman, The (Postino, Il)',
 "Mr. Holland's Opus",
 'From Dusk Till Dawn',
 'Broken Arrow',
 'Happy Gilmore',
 'Muppet Treasure Island',
 'Braveheart',
 'Taxi Driver',
 'Rumble in the Bronx (Hont faan kui)',
 'Birdcage, The',
 'Bad Boys',
 'Apollo 13',
 'Rob Roy',
 'Batman Forever',
 'Casper',
 'Congo',
 'Crimson Tide',
 'Desperado',
 'Die Hard: With a Vengeance',
 'First Knight',
 'Hackers',
 'Johnny Mnemonic',
 'Judge Dredd',
 'Mallrats',
 'Net, The',
 'Nine Months',
 'Species',
 'Waterworld',
 'Billy Madison',
 'Clerks',
 'Don Juan DeMarco',
 'Disclosure',
 'Dumb & Dumber (Dumb and Dumber)',
 'Ed Wood',
 'French Kiss',
 'Hoop Dreams',
 'Interview with the Vampire: The Vampire Chronicles',
 'Junior',
 'Star Wars: Episode IV - A New Hope',
 'Little Women',
 'Like Water for Chocolate (Como agua para chocolate)',
 'Legends of the Fall',
 'Miracle on 34th Street',
 'Nell',
 'Natural Born Killers',
 'Outbreak',
 'Léon: The Professional (a.k.a. The Professional) (Léon)',
 'Pulp Fiction',
 'Quiz Show',
 'Quick and the Dead, The',
 'Specialist, The',
 'Stargate',
 'Santa Clause, The',
 'Shawshank Redemption, The',
 'Tank Girl',
 'Star Trek: Generations',
 'Tommy Boy',
 "What's Eating Gilbert Grape",
 'While You Were Sleeping',
 "Muriel's Wedding",
 'Ace Ventura: Pet Detective',
 'Adventures of Priscilla, Queen of the Desert, The',
 'Clear and Present Danger',
 'Client, The',
 'Crow, The',
 'Flintstones, The',
 'Forrest Gump',
 'Four Weddings and a Funeral',
 'Lion King, The',
 'Mask, The',
 'Maverick',
 'Naked Gun 33 1/3: The Final Insult',
 'River Wild, The',
 'Speed',
 'True Lies',
 'Addams Family Values',
 'Beverly Hills Cop III',
 "Carlito's Way",
 "City Slickers II: The Legend of Curly's Gold",
 'Cliffhanger',
 'Coneheads',
 'Dave',
 'Dazed and Confused',
 'Demolition Man',
 'Firm, The',
 'Free Willy',
 'Fugitive, The',
 'Hot Shots! Part Deux',
 'Hudsucker Proxy, The',
 'In the Line of Fire',
 'In the Name of the Father',
 'Jurassic Park',
 'Last Action Hero',
 'Executive Decision',
 'Much Ado About Nothing',
 'Mrs. Doubtfire',
 'Philadelphia',
 'Piano, The',
 'Remains of the Day, The',
 'Robin Hood: Men in Tights',
 "Schindler's List",
 'Searching for Bobby Fischer',
 'Sleepless in Seattle',
 'Blade Runner',
 'So I Married an Axe Murderer',
 'Nightmare Before Christmas, The',
 'Three Musketeers, The',
 'Tombstone',
 'True Romance',
 'Brady Bunch Movie, The',
 'Home Alone',
 'Ghost',
 'Aladdin',
 'Terminator 2: Judgment Day',
 'Dances with Wolves',
 'Batman',
 'Silence of the Lambs, The',
 'Snow White and the Seven Dwarfs',
 'Beauty and the Beast',
 'Pinocchio',
 'Pretty Woman',
 'Fargo',
 'Primal Fear',
 'Courage Under Fire',
 'Mission: Impossible',
 'Dragonheart',
 'James and the Giant Peach',
 'Space Jam',
 'Truth About Cats & Dogs, The',
 'Multiplicity',
 'Wallace & Gromit: The Best of Aardman Animation',
 'Craft, The',
 'Rock, The',
 'Twister',
 'Ghost in the Shell (Kôkaku kidôtai)',
 'Spy Hard',
 'Wallace & Gromit: A Close Shave',
 'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
 'Striptease',
 'Trainspotting',
 'Independence Day (a.k.a. ID4)',
 'Hunchback of Notre Dame, The',
 'Cable Guy, The',
 'Kingpin',
 'Eraser',
 'Nutty Professor, The',
 'Frighteners, The',
 'Phenomenon',
 'Time to Kill, A',
 'Ransom',
 'Escape from L.A.',
 'Tin Cup',
 'Godfather, The',
 'Island of Dr. Moreau, The',
 "Singin' in the Rain",
 "Breakfast at Tiffany's",
 'Vertigo',
 'Rear Window',
 'North by Northwest',
 'Some Like It Hot',
 'Casablanca',
 'Maltese Falcon, The',
 'My Fair Lady',
 'Wizard of Oz, The',
 'Gone with the Wind',
 'Citizen Kane',
 '2001: A Space Odyssey',
 "It's a Wonderful Life",
 'Night of the Living Dead',
 'African Queen, The',
 'Cinderella',
 'Robin Hood: Prince of Thieves',
 'Mary Poppins',
 'Dumbo',
 'Alice in Wonderland',
 'Sound of Music, The',
 'Die Hard',
 'Lawnmower Man, The',
 'That Thing You Do!',
 'Long Kiss Goodnight, The',
 "William Shakespeare's Romeo + Juliet",
 'Swingers',
 'Sleepers',
 'Willy Wonka & the Chocolate Factory',
 'Sleeper',
 'Fish Called Wanda, A',
 "Monty Python's Life of Brian",
 'Bonnie and Clyde',
 'Dirty Dancing',
 'Reservoir Dogs',
 'Platoon',
 'Basic Instinct',
 'Crying Game, The',
 'E.T. the Extra-Terrestrial',
 'Top Gun',
 'People vs. Larry Flynt, The',
 'Abyss, The',
 'Escape from New York',
 'Monty Python and the Holy Grail',
 'Wallace & Gromit: The Wrong Trousers',
 'Cinema Paradiso (Nuovo cinema Paradiso)',
 'Delicatessen',
 'English Patient, The',
 'Strictly Ballroom',
 "One Flew Over the Cuckoo's Nest",
 'Star Wars: Episode V - The Empire Strikes Back',
 'Princess Bride, The',
 'Raiders of the Lost Ark (Indiana Jones and the Raiders of the Lost Ark)',
 'Brazil',
 'Aliens',
 'Good, the Bad and the Ugly, The (Buono, il brutto, il cattivo, Il)',
 '12 Angry Men',
 'Lawrence of Arabia',
 'Clockwork Orange, A',
 'To Kill a Mockingbird',
 'Apocalypse Now',
 'Star Wars: Episode VI - Return of the Jedi',
 'Third Man, The',
 'Goodfellas',
 'Alien',
 'Army of Darkness',
 'Psycho',
 'Blues Brothers, The',
 'Godfather: Part II, The',
 'Full Metal Jacket',
 'Grand Day Out with Wallace and Gromit, A',
 'Amadeus',
 'Raging Bull',
 'Annie Hall',
 'Boot, Das (Boat, The)',
 'Sting, The',
 'Terminator, The',
 'Glory',
 'Manhattan',
 'Dead Poets Society',
 'Graduate, The',
 'Femme Nikita, La (Nikita)',
 'Bridge on the River Kwai, The',
 'Chinatown',
 'Shining, The',
 'Stand by Me',
 'Evil Dead II (Dead by Dawn)',
 'Great Escape, The',
 'Deer Hunter, The',
 'Groundhog Day',
 'Unforgiven',
 'Manchurian Candidate, The',
 'Arsenic and Old Lace',
 'Back to the Future',
 'Fried Green Tomatoes',
 'Patton',
 'Akira',
 'Highlander',
 'Cool Hand Luke',
 'Young Frankenstein',
 'Fantasia',
 'Heathers',
 'Ben-Hur',
 'This Is Spinal Tap',
 'Indiana Jones and the Last Crusade',
 'Gandhi',
 'Room with a View, A',
 'Pink Floyd: The Wall',
 'Field of Dreams',
 'Butch Cassidy and the Sundance Kid',
 'When Harry Met Sally...',
 'Alien³ (a.k.a. Alien 3)',
 'American Werewolf in London, An',
 'Birds, The',
 "Dracula (Bram Stoker's Dracula)",
 'Cape Fear',
 'Carrie',
 'Nightmare on Elm Street, A',
 'Star Trek: First Contact',
 'Sling Blade',
 '101 Dalmatians',
 'Die Hard 2',
 'Star Trek: The Motion Picture',
 'Star Trek VI: The Undiscovered Country',
 'Star Trek II: The Wrath of Khan',
 'Star Trek III: The Search for Spock',
 'Star Trek IV: The Voyage Home',
 'Batman Returns',
 'Young Guns',
 'Grease',
 'Under Siege',
 'Jaws',
 'Mars Attacks!',
 'Jerry Maguire',
 'Raising Arizona',
 'Sneakers',
 'Beavis and Butt-Head Do America',
 'Scream',
 'Last of the Mohicans, The',
 "Dante's Peak",
 'Donnie Brasco',
 'Saint, The',
 'Liar Liar',
 'Anaconda',
 'Grosse Pointe Blank',
 'Austin Powers: International Man of Mystery',
 'Fifth Element, The',
 'Lost World: Jurassic Park, The',
 'Con Air',
 'Batman & Robin',
 "My Best Friend's Wedding",
 'Face/Off',
 'Men in Black (a.k.a. MIB)',
 'Contact',
 'Conan the Barbarian',
 'Event Horizon',
 'Conspiracy Theory',
 'Air Force One',
 'Hunt for Red October, The',
 'L.A. Confidential',
 'Game, The',
 'Chasing Amy',
 'Full Monty, The',
 "Devil's Advocate, The",
 'Gattaca',
 'Stripes',
 'Boogie Nights',
 'Witness',
 'Starship Troopers',
 'Truman Show, The',
 'Alien: Resurrection',
 'Good Will Hunting',
 'Titanic',
 'Tomorrow Never Dies',
 'Jackie Brown',
 'Big Lebowski, The',
 'Wag the Dog',
 'Dark City',
 'Wedding Singer, The',
 'As Good as It Gets',
 'Lost in Space',
 'Deep Impact',
 'X-Files: Fight the Future, The',
 'Out of Sight',
 'Armageddon',
 'Lethal Weapon 4',
 'Pi',
 "There's Something About Mary",
 'West Side Story',
 'Midnight Cowboy',
 'French Connection, The',
 'Rocky',
 'Last Emperor, The',
 'Rain Man',
 'Driving Miss Daisy',
 'Labyrinth',
 'Breakfast Club, The',
 'Halloween',
 'Poltergeist',
 'Exorcist, The',
 'Lethal Weapon',
 'Lethal Weapon 2',
 'Lethal Weapon 3',
 'Gremlins',
 'Goonies, The',
 'Mask of Zorro, The',
 'Back to the Future Part II',
 'Back to the Future Part III',
 'Bambi',
 'Seven Samurai (Shichinin no samurai)',
 'Dune',
 'Godfather: Part III, The',
 'Saving Private Ryan',
 'Honey, I Shrunk the Kids',
 'Negotiator, The',
 'Blue Velvet',
 'Jungle Book, The',
 'Lady and the Tramp',
 'Little Mermaid, The',
 '101 Dalmatians (One Hundred and One Dalmatians)',
 'Rocketeer, The',
 'Sleeping Beauty',
 'Splash',
 'Tron',
 'Indiana Jones and the Temple of Doom',
 'Addams Family, The',
 'Dark Crystal, The',
 'Sixteen Candles',
 'NeverEnding Story, The',
 'Blade',
 'Beetlejuice',
 'Willow',
 'Untouchables, The',
 'Say Anything...',
 'Few Good Men, A',
 'Rush Hour',
 'Ronin',
 'Thing, The',
 'Player, The',
 'Edward Scissorhands',
 'Antz',
 'My Cousin Vinny',
 'Pleasantville',
 'Life Is Beautiful (La Vita è bella)',
 'American History X',
 'Elizabeth',
 'Big Chill, The',
 'Enemy of the State',
 "Bug's Life, A",
 'Fletch',
 'Simple Plan, A',
 'Star Trek: Insurrection',
 'Rushmore',
 'Shakespeare in Love',
 'Romancing the Stone',
 'Cocoon',
 'Karate Kid, The',
 "You've Got Mail",
 'Thin Red Line, The',
 'Fly, The',
 'Crocodile Dundee',
 '¡Three Amigos!',
 'Payback',
 'October Sky',
 'Office Space',
 'Planet of the Apes',
 'Analyze This',
 'Cruel Intentions',
 'Lock, Stock & Two Smoking Barrels',
 'Matrix, The',
 '10 Things I Hate About You',
 'Election',
 'Entrapment',
 'Dick Tracy',
 'Mummy, The',
 'Star Wars: Episode I - The Phantom Menace',
 'Superman',
 'Superman II',
 'Rocky Horror Picture Show, The',
 'Notting Hill',
 'Austin Powers: The Spy Who Shagged Me',
 'Run Lola Run (Lola rennt)',
 'Big Daddy',
 'Arachnophobia',
 'South Park: Bigger, Longer and Uncut',
 'Wild Wild West',
 'American Pie',
 'Arlington Road',
 'Blair Witch Project, The',
 'Eyes Wide Shut',
 'Ghostbusters (a.k.a. Ghost Busters)',
 'Ghostbusters II',
 'Deep Blue Sea',
 'Mystery Men',
 'Little Shop of Horrors',
 'Iron Giant, The',
 'Sixth Sense, The',
 'Thomas Crown Affair, The',
 'Bowfinger',
 'Airplane!',
 'Big',
 'Christmas Story, A',
 '13th Warrior, The',
 'American Beauty',
 'Deliverance',
 'Excalibur',
 'Three Kings',
 'Risky Business',
 'Total Recall',
 "Ferris Bueller's Day Off",
 'Dirty Dozen, The',
 'Goldfinger',
 'From Russia with Love',
 'Dr. No',
 'Fistful of Dollars, A (Per un pugno di dollari)',
 'Fight Club',
 'Time Bandits',
 'RoboCop',
 'Who Framed Roger Rabbit?',
 'Being John Malkovich',
 'Princess Mononoke (Mononoke-hime)',
 'Insider, The',
 'Falling Down',
 'Spaceballs',
 'Trading Places',
 'Dogma',
 'Moonstruck',
 'Sleepy Hollow',
 'World Is Not Enough, The',
 'Fatal Attraction',
 'Fisher King, The',
 'Toy Story 2',
 'Green Mile, The',
 'Magnolia',
 'Galaxy Quest',
 'Talented Mr. Ripley, The',
 'Fast Times at Ridgemont High',
 'Sister Act',
 "Wayne's World",
 'League of Their Own, A',
 'Patriot Games',
 'Boondock Saints, The',
 'Pitch Black',
 'American Graffiti',
 'Erin Brockovich',
 'Thelma & Louise',
 'Animal House',
 'Good Morning, Vietnam',
 'Close Encounters of the Third Kind',
 'High Fidelity',
 'Hook',
 'Misery',
 'Frequency',
 'Predator',
 'American Psycho',
 'Caddyshack',
 'U-571',
 'Gladiator',
 'Road Trip',
 'Mission: Impossible II',
 'Shanghai Noon',
 'Blazing Saddles',
 'Mad Max',
 'Road Warrior, The (Mad Max 2)',
 'Gone in 60 Seconds',
 'Chicken Run',
 'Me, Myself & Irene',
 'Patriot, The',
 'Perfect Storm, The',
 'Scary Movie',
 'X-Men',
 'Almost Famous',
 'Best in Show',
 'Remember the Titans',
 'Meet the Parents',
 'Requiem for a Dream',
 "Charlie's Angels",
 'Unbreakable',
 'Crouching Tiger, Hidden Dragon (Wo hu cang long)',
 'Planes, Trains & Automobiles',
 'Snatch',
 'Chocolat',
 'What Women Want',
 'Cast Away',
 'Miss Congeniality',
 'O Brother, Where Art Thou?',
 'Traffic',
 'Beverly Hills Cop',
 'Lost Boys, The',
 'Enemy at the Gates',
 'Memento',
 "Bridget Jones's Diary",
 'Scarface',
 'Mummy Returns, The',
 "Knight's Tale, A",
 'Shrek',
 'Moulin Rouge',
 'Pearl Harbor',
 'City Slickers',
 'Lara Croft: Tomb Raider',
 'Fast and the Furious, The',
 'A.I. Artificial Intelligence',
 'Legally Blonde',
 "Bill & Ted's Excellent Adventure",
 'Planet of the Apes',
 'Rush Hour 2',
 'American Pie 2',
 'Others, The',
 'Jay and Silent Bob Strike Back',
 'Training Day',
 'Zoolander',
 'Mulholland Drive',
 'Donnie Darko',
 'Monsters, Inc.',
 "Harry Potter and the Sorcerer's Stone (a.k.a. Harry Potter and the Philosopher's Stone)",
 "Ocean's Eleven",
 "Amelie (Fabuleux destin d'Amélie Poulain, Le)",
 'Vanilla Sky',
 'Royal Tenenbaums, The',
 'Lord of the Rings: The Fellowship of the Ring, The',
 'Beautiful Mind, A',
 'Black Hawk Down',
 'M*A*S*H (a.k.a. MASH)',
 'Ice Age',
 'My Big Fat Greek Wedding',
 'Spider-Man',
 'About a Boy',
 'Star Wars: Episode II - Attack of the Clones',
 'Bourne Identity, The',
 'Minority Report',
 'Men in Black II (a.k.a. MIIB) (a.k.a. MIB 2)',
 'Road to Perdition',
 'Austin Powers in Goldmember',
 'Signs',
 'Spirited Away (Sen to Chihiro no kamikakushi)',
 'Bowling for Columbine',
 'Ring, The',
 'Harry Potter and the Chamber of Secrets',
 'Adaptation',
 'Equilibrium',
 'Lord of the Rings: The Two Towers, The',
 'Gangs of New York',
 'Catch Me If You Can',
 'Chicago',
 'Pianist, The',
 'City of God (Cidade de Deus)',
 'X2: X-Men United',
 'Matrix Reloaded, The',
 'Finding Nemo',
 'Italian Job, The',
 '28 Days Later',
 'Terminator 3: Rise of the Machines',
 'Pirates of the Caribbean: The Curse of the Black Pearl',
 'Lost in Translation',
 "Monty Python's The Meaning of Life",
 'School of Rock',
 'Mystic River',
 'Kill Bill: Vol. 1',
 'Matrix Revolutions, The',
 'Love Actually',
 'Hero (Ying xiong)',
 'Last Samurai, The',
 'Big Fish',
 'Lord of the Rings: The Return of the King, The',
 'The Butterfly Effect',
 '50 First Dates',
 'Eternal Sunshine of the Spotless Mind',
 'Hellboy',
 'Kill Bill: Vol. 2',
 'Troy',
 'Shrek 2',
 'Harry Potter and the Prisoner of Azkaban',
 'Dodgeball: A True Underdog Story',
 'Spider-Man 2',
 'Anchorman: The Legend of Ron Burgundy',
 'I, Robot',
 'Bourne Supremacy, The',
 'Garden State',
 'Collateral',
 'Shaun of the Dead',
 'Sideways',
 'Incredibles, The',
 'Old Boy',
 'Million Dollar Baby',
 'Hotel Rwanda',
 'Sin City',
 'Crash',
 'Star Wars: Episode III - Revenge of the Sith',
 'Mr. & Mrs. Smith',
 'Batman Begins',
 'Serenity',
 '40-Year-Old Virgin, The',
 'Lord of War',
 'Harry Potter and the Goblet of Fire',
 'V for Vendetta',
 'Thank You for Smoking',
 'Inside Man',
 'Lucky Number Slevin',
 'X-Men: The Last Stand',
 "Pirates of the Caribbean: Dead Man's Chest",
 'Little Miss Sunshine',
 'Illusionist, The',
 'Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan',
 "Pan's Labyrinth (Laberinto del fauno, El)",
 'Departed, The',
 'Children of Men',
 'Prestige, The',
 'Casino Royale',
 'Blood Diamond',
 'Ratatouille',
 'Hot Fuzz',
 '300',
 "Pirates of the Caribbean: At World's End",
 'Simpsons Movie, The',
 'Bourne Ultimatum, The',
 'Superbad',
 'American Gangster',
 'No Country for Old Men',
 'I Am Legend',
 'Juno',
 'In Bruges',
 'Dark Knight, The',
 'Iron Man',
 'Taken',
 'Kung Fu Panda',
 'WALL·E',
 'Watchmen',
 'Slumdog Millionaire',
 'Gran Torino',
 'Inglourious Basterds',
 'Moon',
 'Star Trek',
 'Up',
 'Hangover, The',
 '(500) Days of Summer',
 'District 9',
 'Zombieland',
 'Avatar',
 'Sherlock Holmes',
 'Shutter Island',
 'Inception',
 "King's Speech, The",
 'Avengers, The',
 'Dark Knight Rises, The',
 'Django Unchained',
 'Interstellar']

In [589]:
# for i in movies_list:
#     # print(i)
#     recommend(i)
#     # print('')

In [590]:
# similarity2=cosine_similarity(vector3)

In [591]:
# similarity2.shape

In [592]:
# def recommend2(movie):
#     movie_id = df.loc[df['title']==movie,'movieId'].iloc[0]
#     print(movie_id)
#     # row_number=vector.index.get_loc(movie_id)
#     # print(row_number)
#     # distances=similarity2[row_number]
#     # recommended_movie_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:11]


#     # for i in recommended_movie_list:
#     #     # print(i[0])
#     #     new_movie_id= vector.index[i[0]]
#     #     # print(new_movie_id)
        
#         # print(df.loc[df['movieId']==new_movie_id,'title'].iloc[0])

In [593]:
import pickle

In [595]:
pickle.dump(movies_list,open('movies_list.pkl','wb'))

In [596]:
pickle.dump(df,open('df.pkl','wb'))

In [597]:
pickle.dump(vector,open('vector.pkl','wb'))

In [598]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [599]:
pickle.dump(df.to_dict(),open('df_dict.pkl','wb'))

In [600]:
pickle.dump(vector.to_dict(),open('vector_dict.pkl','wb'))